services:
  project-service:
    instances:
      - url: http://127.0.0.1:8002
        weight: 1
        healthy: true
    health_check:
      path: /health
      interval: 30
      timeout: 5
      
  auth-service:
    instances:
      - url: http://127.0.0.1:8000
        weight: 1
        healthy: true
    health_check:
      path: /health
      interval: 30
      timeout: 5
      
  ecs-service:
    instances:
      - url: http://ecs-service-1:8000
        weight: 1
        healthy: true
    health_check:
      path: /health
      interval: 30
      timeout: 5
      
  dashboard-service:
    instances:
      - url: http://dashboard-service-1:8000
        weight: 1
        healthy: true
    health_check:
      path: /health
      interval: 30
      timeout: 5
